### ISSUE TITLE
Unable to install - unclear - white screen

### ISSUE THREAD

**Issue by anthonyh29** [andreioprisan/igroups#4]
I've attempted for a while to install this in a LAMP server - hosted on Digital Ocean (so no problems there) but whenever I move the files across and open a browser - instead of seeing installation I see a blank screen and a 'not found' error as it automatically attemps to default to /auth/logout.

**Comment by mat2538** [comment]
I have the same problem. Did you find the solution?

**Comment by andreioprisan** [comment]
Are you sure your setup meets all the prerequisites as listed on http://www.openvbx.org/install/?
This setup does not go through the installation steps that would check for all the dependencies, so please check that. 
Also, can you provide any logs as to what may not be working? Did you do the database import and the right database credentials set up so that the application can connect to it?

**Comment by mat2538** [comment]
Hello ,
I will explain my approach. I start by installing the "official" version of
OPENVBX , just to make test and be sure I had all the prerequisites for
OpenVBX. And worked. Then I do the same thing with your version . I upload
the file on my server , I changed the credidential in the config file and
import the sql file with phpmyadmin. But when I access to the root
directory of the site with my browser, the installation not start. I am
rather redirected to "logout " . Is what I forget a step ? Can you explain
the process in detail ?
Thank you!
